### ISSUE TITLE
What kind of open source license does your code belong to?

### ISSUE THREAD

**Issue by gitsrc** [pastoapp/asteroid-server#1]
Excuse me, is this code copyrighted, because I didn't see the open source license file.

**Comment by valerius21** [comment]
Hi @gitsrc !

This repository is still under construction. I have not been able to find the time to add all the mandatory copyright mentions to it. 
Because this source code, and resulting software is still on a level of proof-of-concept, they'll remain under copyright until I make up my mind about a fitting license. 

If you want to use the source code in the meantime, feel free to email me so we can have a quick chat about it. My website and contact information are on my bio. :)

Also, I'll let you know in this issue when a license is added to the project.

Cheers!

**Comment by gitsrc** [comment]
> Hi @gitsrc !
> 
> This repository is still under construction. I have not been able to find the time to add all the mandatory copyright mentions to it. Because this source code, and resulting software is still on a level of proof-of-concept, they'll remain under copyright until I make up my mind about a fitting license.
> 
> If you want to use the source code in the meantime, feel free to email me so we can have a quick chat about it. My website and contact information are on my bio. :)
> 
> Also, I'll let you know in this issue when a license is added to the project.
> 
> Cheers!

thanks 🤝
